name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.0

      - name: Install dependencies
        run: go mod tidy

      - name: Run migrator
        run: go run ./cmd/migrator --storage=./youtube.db --migrations=./migrations

      - name: Start server
        run: |
          nohup go run ./cmd/server/main.go > server.log 2>&1 &
          SERVER_PID=$!
          echo "Server started with PID $SERVER_PID"
          sleep 5

      - name: Run client (async)
        run: |
          go run ./cmd/client/main.go --async https://www.youtube.com/watch?v=e_pY0btswmk https://www.youtube.com/watch?v=bcwpkiXlpno
          echo "Async client finished"

      - name: Run client (sync)
        run: |
          go run ./cmd/client/main.go https://www.youtube.com/watch?v=W40PJ_GnbBE
          echo "Sync client finished"

      - name: Stop server
        run: |
          if [ -n "$SERVER_PID" ]; then
            kill $SERVER_PID
            echo "Server stopped"
          fi
